# version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - sqlserver
    environment:
      DB_CONNECTION: sqlsrv
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_DATABASE: laravel_db
      DB_USERNAME: sa
      DB_PASSWORD: MiPassword2024

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "MiPassword2024"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
volumes:
  sqlserver_data: